import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Skills from '../components/Skills'
import Tools from '../components/Tools'
import About from '../components/About'
import Projects from '../components/Projects'
import Hobbies from '../components/Hobbies'
import Contact from '../components/Contact'

import { useTheme } from 'next-themes'
import { useEffect, useRef, useState } from 'react'

export default function Home() {

  const [mounted, setMounted] = useState(false);
  const {theme, setTheme} = useTheme();
  
  useEffect(() => {
    setMounted(true)
    setTheme('light')
  }, [])
  const ref = useRef(false);

  const handleChange = () => {
    if (theme === 'dark'){
      setTheme('light')
    }
    if (theme === 'light'){
      setTheme('dark')
    }
  }

  if(!mounted){
    return null
  } 

  return (
    <div>
      <Head>
        <title>Mon Portfolio | Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="drawer">
        <input id="my-drawer-3" type="checkbox" className="drawer-toggle" /> 
        <div className="drawer-content flex flex-col">
          {/* <!-- Navbar --> */}
          <div className="w-full z-10 navbar sticky top-0 bg-base-300 dark:bg-gray-900 dark:text-white">
            <div className="flex-none lg:hidden">
              <label htmlFor="my-drawer-3" className="btn btn-square btn-ghost">
                <svg 
                  xmlns="http://www.w3.org/2000/svg" 
                  fill="none" 
                  viewBox="0 0 24 24" 
                  className="inline-block w-6 h-6 stroke-current">
                    <path 
                      strokeLinecap="round" 
                      strokeLinejoin="round" 
                      strokeWidth="2" 
                      d="M4 6h16M4 12h16M4 18h16">
                    </path>
                </svg>
              </label>
            </div> 
            <div className="flex-1 px-2 mx-2 justify-between">
              <Link href={'#home'}><a>Accueil</a></Link>
              <label className="swap swap-rotate">
                {/* <!-- this hidden checkbox controls the state --> */}
                <input ref={ref} id="swaper" type="checkbox" onChange={(handleChange)} />
                {/* <!-- sun icon --> */}
                <svg className="swap-on fill-yellow-400 w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"/></svg>
                {/* <!-- moon icon --> */}
                <svg className="swap-off fill-indigo-800 w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"/></svg>
              </label>
            </div>
            <div className="flex-none hidden lg:block">
              <ul className="menu menu-horizontal">
                {/* <!-- Navbar menu content here --> */}
                <li><Link href={'#skills'}><a className='hover:bg-[#ffb703]'>Technologies</a></Link></li>
                <li><Link href={'#projects'}><a className='hover:bg-[#ffb703]'>Projets</a></Link></li>
                <li><Link href={'#about'}><a className='hover:bg-[#ffb703]'>A Propos</a></Link></li>
                {/* <li><Link href={'#hobbies'}><a className='hover:bg-[#ffb703]'>Hobbies</a></Link></li> */}
                <li><Link href={'#contact'}><a className='hover:bg-[#ffb703]'>Contact</a></Link></li>
              </ul>
            </div>
          </div>
          {/* <!-- Page content here --> */}
          <main className={styles.main}>
            <section id="home" className={styles.homepage}>
              <div className="flex flex-col justify-center items-center h-[100vh]">
                <h1 className='text-white text-3xl lg:text-4xl'>Salut !</h1>
                <h2 className='text-white text-3xl lg:text-4xl'>
                  <div className={styles.typed_out}>
                  Je suis Développeur Front-End !
                  </div>
                </h2>
              </div>
            </section>
            <div className='w-full flex flex-col lg:flex-row justify-center'>
              <Skills/>
              <Tools/>
            </div>
            <Projects/>
            <About/>
            {/* <Hobbies/> */}
            <Contact/>
          </main>
          <footer className={styles.footer}>
            <p>Copyright © 2022 - Tous droits réservés - Créé avec 
              <span className="mx-1">
                <a
                  href="https://nextjs.org/"
                  target="_blank"
                  rel="noreferrer"
                  >
                    <Image
                      src="/next.svg"
                      title='Next.js'
                      alt="Image"
                      width={20}
                      height={20}
                      reponsive="true"
                    />
                </a>
              </span>
            </p>
          </footer>
        </div> 
        <div className="drawer-side">
          <label htmlFor="my-drawer-3" className="drawer-overlay"></label> 
            <ul className="menu p-4 overflow-y-auto w-80 bg-base-100">
              {/* <!-- Sidebar content here --> */}
              <li><Link href={'#skills'}><a>Technologies</a></Link></li>
              <li><Link href={'#projects'}><a>Projets</a></Link></li>
              <li><Link href={'#about'}><a>A Propos</a></Link></li>
              {/* <li><Link href={'#hobbies'}><a>Hobbies</a></Link></li> */}
              <li><Link href={'#contact'}><a>Contact</a></Link></li>
            </ul>
        </div>
      </div>
    </div>
  )
}
