import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {

    return (
        <>
            <Head>
                <title>Mon Portfolio | Accueil</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <section id="home" className={styles.homepage}>
                    <div className="flex flex-col justify-center items-center min-h-full">
                        <h1 className='text-white text-3xl lg:text-4xl'>Salut !</h1>
                        <h2 className='text-white text-3xl lg:text-4xl'>
                            <div className={styles.typed_out}>
                                Je suis Développeur Front-End !
                            </div>
                        </h2>
                    </div>
                </section>
            </main>
        </>
    )
}
