import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Skills from "../components/Skills"
import Tools from "../components/Tools"
import Projects from '../components/Projects'
import About from '../components/About'
import Contact from '../components/Contact'



export default function Home() {

    return (
        <>
            <Head>
                <title>Mon Portfolio | Accueil</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <section id="home" className={styles.homepage}>
                    <div className="flex flex-col justify-center items-center min-h-full">
                        <h1 className='text-white text-3xl lg:text-4xl'>Salut !</h1>
                        <h2 className='text-white text-3xl lg:text-4xl'>
                            <div className={styles.typed_out}>
                                Je suis Développeur Front-End !
                            </div>
                        </h2>
                    </div>
                </section>
                <section>
                    <div className="flex flex-col w-screen justify-center items-center bg-[#345ca8] dark:bg-[#023047]">
                        <Skills />
                        <Tools />
                    </div>
                    <Projects/>
                    <About/>
                    <Contact/>
                </section>
            </main>
        </>
    )
}
